version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_cesta
    restart: always
    environment:
      POSTGRES_DB: cesta
      POSTGRES_USER: cesta
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
